f_or_b_choices = {
    'Foods' : 'Foods',
    'Beverages' : 'Beverages',
}

cooking_type_choices = {
    'Baking' : 'Baking',
    'Roasting' : 'Roasting',
    'Grilling' : 'Grilling',
    'Frying' : 'Frying',
    'Boiling' : 'Boiling',
    'Steaming' : 'Steaming',
    'Braising' : 'Braising',
    'Pan_Frying' : 'Pan_Frying', 
    'Stir_Frying' : 'Stir_Frying',
    'Stewing' : 'Stewing',
    'Slow_Cooking' : 'Slow_Cooking',
    'Salad' : 'Salad',
    'Cold_Dish' : 'Cold_Dish',
    'Dessert' : 'Dessert',
    'Soup_Noodle' : 'Soup_Noodle',
    'Others' : 'Others',
}

beverage_choices = {
    'Cold_Drinks' : 'Cold_Drinks',
    'Hot_Drinks' : 'Hot_Drinks',
    'Water' : 'Water',
    'Soft_Drinks' : 'Soft_Drinks',
    'Juices' : 'Juices',
    'Coffee' : 'Coffee',
    'Tea' : 'Tea',
    'Milkshakes' : 'Milkshakes',
    'Smoothies' : 'Smoothies',
    'Leung_Cha' : 'Leung_Cha',
    'Cocktails' : 'Cocktails',
    'Mocktails' : 'Mocktails',
    'Alcoholic_Drinks' : 'Alcoholic_Drinks',
    'Beers' : 'Beers',
    'Wines' : 'Wines',
    'Spirits' : 'Spirits',
    'Functional_Drinks' : 'Functional_Drinks',
    'Others' : 'Others',
}

district_choices = {
'Islands' : 'Islands',
'Kwai Tsing' : 'Kwai Tsing',
'North' : 'North',
'Sai Kung' : 'Sai Kung',
'Sha Tin' : 'Sha Tin',
'Tai Po' : 'Tai Po',
'Tsuen Wan' : 'Tsuen Wan',
'Tuen Mun' : 'Tuen Mun',
'Yuen Long' : 'Yuen Long',
'Kowloon City' : 'Kowloon City',
'Kwun Tong' : 'Kwun Tong',
'Sham Shui Po' : 'Sham Shui Po',
'Wong Tai Sin' : 'Wong Tai Sin',
'Yau Tsim Mong' : 'Yau Tsim Mong',
'Central & Western' : 'Central & Western',
'Eastern' : 'Eastern',
'Southern' : 'Southern',
'Wan Chai' : 'Wan Chai',
}

cuisine_choices = {
'Japanese' : 'Japanese',
'Chinese' : 'Chinese',
'Thai' : 'Thai',
'Italian' : 'Italian',
'Mexican' : 'Mexican',
'Korean' : 'Korean',
'Vietnamese' : 'Vietnamese' ,
'French' : 'French',
'American': 'American',
'Taiwanese' : 'Taiwanese',
'Canadian' : 'Canadian',
'Singapore' : 'Singapore',
'Malaysian' : 'Malaysian',
'Filipino' : 'Filipino',
'Other' : 'Other',
} 