# Generated by Django 5.2 on 2026-08-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F_and_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True)),
                ('F_or_b', models.CharField(max_length=50)),
                ('cooking_type', models.CharField(max_length=50)),
                ('beverage_type', models.CharField(max_length=50)),
                ('veggie', models.BooleanField(default=False)),
                ('halal', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('allegy_ingredient', models.CharField(blank=True, max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-list_date'],
                'indexes': [models.Index(fields=['list_date'], name='f_and_b_f_a_list_da_abf437_idx')],
            },
        ),
    ]
