# Generated by Django 5.2 on 2026-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_and_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_and_b',
            name='F_or_b',
            field=models.CharField(choices=[('Foods', 'Foods'), ('Beverages', 'Beverages')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='f_and_b',
            name='beverage_type',
            field=models.CharField(blank=True, choices=[('Cold_Drinks', 'Cold_Drinks'), ('Hot_Drinks', 'Hot_Drinks'), ('Water', 'Water'), ('Soft_Drinks', 'Soft_Drinks'), ('Juices', 'Juices'), ('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Milkshakes', 'Milkshakes'), ('Smoothies', 'Smoothies'), ('Leung_Cha', 'Leung_Cha'), ('Cocktails', 'Cocktails'), ('Mocktails', 'Mocktails'), ('Alcoholic_Drinks', 'Alcoholic_Drinks'), ('Beers', 'Beers'), ('Wines', 'Wines'), ('Spirits', 'Spirits'), ('Functional_Drinks', 'Functional_Drinks'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='f_and_b',
            name='cooking_type',
            field=models.CharField(blank=True, choices=[('Baking', 'Baking'), ('Roasting', 'Roasting'), ('Grilling', 'Grilling'), ('Frying', 'Frying'), ('Boiling', 'Boiling'), ('Steaming', 'Steaming'), ('Braising', 'Braising'), ('Pan_Frying', 'Pan_Frying'), ('Stir_Frying', 'Stir_Frying'), ('Stewing', 'Stewing'), ('Slow_Cooking', 'Slow_Cooking'), ('Salad', 'Salad'), ('Cold_Dish', 'Cold_Dish'), ('Dessert', 'Dessert'), ('Soup_Noodle', 'Soup_Noodle'), ('Others', 'Others')], default='', max_length=50),
        ),
    ]
