# Generated by Django 5.2 on 2026-08-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('cuisine_choices', models.CharField(max_length=50)),
                ('acommodate', models.IntegerField(blank=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_delivery', models.BooleanField(default=True)),
                ('average_spend', models.IntegerField(blank=True)),
                ('promo_badge_text', models.CharField(blank=True, max_length=100, null=True)),
                ('accept_reservations', models.BooleanField(default=True)),
                ('pre_order', models.BooleanField(default=True)),
                ('catering_service', models.BooleanField(default=False)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('has_Whatspp', models.BooleanField(default=True)),
                ('opening_hours', models.TimeField(default=None)),
                ('closing_hours', models.TimeField(default=None)),
                ('rating', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('signature_dish', models.CharField(blank=True, max_length=200)),
                ('sign_dish_photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('sign_dish_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('sign_dish_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-list_date'],
                'indexes': [models.Index(fields=['list_date'], name='merchants_m_list_da_da135c_idx')],
            },
        ),
    ]
