# Generated by Django 5.2 on 2026-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchant_cuisine_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='acommodate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
