# Generated by Django 5.2 on 2026-08-01 19:36

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True)),
                ('origin', django_countries.fields.CountryField(max_length=2)),
                ('package_size', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-list_date'],
                'indexes': [models.Index(fields=['list_date'], name='products_pr_list_da_4bbb7a_idx')],
            },
        ),
    ]
